-- Esquema
CREATE TABLE IF NOT EXISTS inventory (
  sku TEXT PRIMARY KEY,
  available_qty INTEGER NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGSERIAL PRIMARY KEY,
  order_id TEXT UNIQUE NOT NULL,
  sku TEXT NOT NULL,
  qty INTEGER NOT NULL CHECK (qty > 0),
  customer_id TEXT NOT NULL,
  received_at TIMESTAMP NOT NULL DEFAULT NOW()
);


INSERT INTO inventory (sku, available_qty) VALUES
-- Analgésicos
('MED-ANALG-ACETAM-500MG-24TAB', 120),
('MED-ANALG-ACETAM-650MG-10TAB', 30),
('MED-ANALG-IBUPRO-400MG-20CAP', 75),
('MED-ANALG-NAPROX-250MG-20TAB', 45),

-- Gastro
('MED-GI-OMEPRA-20MG-14CAP', 60),
('MED-GI-PANTOP-40MG-28TAB', 25),
('MED-GI-LOPERA-2MG-12CAP', 10),

-- Alergia
('MED-ALERG-LORATA-10MG-10TAB', 80),
('MED-ALERG-CETIRI-10MG-20TAB', 50),
('MED-ALERG-DIPHEN-25MG-24CAP', 15),

-- Antibióticos
('MED-ANTIB-AMOXI-500MG-12CAP', 5),
('MED-ANTIB-AZITH-500MG-3TAB', 0),     -- agotado
('MED-ANTIB-CEFAL-500MG-12CAP', 8),

-- Respiratorio (inhaladores)
('MED-RESP-SALBUT-100MCG-200D', 22),
('MED-RESP-BECLOM-50MCG-200D', 12),
('MED-RESP-BUDESO-200MCG-200D', 6),

-- Diabetes
('MED-DIAB-METFOR-850MG-60TAB', 100),
('MED-DIAB-GLIBEN-5MG-30TAB', 20),
('MED-DIAB-INSUGL-100UML-10ML', 3),

-- Cardiometabólico
('MED-CARD-LOSART-50MG-30TAB', 90),
('MED-CARD-ENALAP-10MG-30TAB', 40),
('MED-CARD-ATORVA-20MG-30TAB', 35),

-- Dermatología
('MED-DERM-CLOT-CREMA-20G', 18),
('MED-DERM-HYDROC-1PCT-30G', 7),
('MED-DERM-MUPIRO-2PCT-15G', 0),        -- agotado

-- Tos y resfriado
('MED-ANTITUSS-DEXTRO-120ML', 14),
('MED-ANTITUSS-AMBROX-15MG5ML-120ML', 21),

-- Laxantes
('MED-LAX-SENNOS-8P6MG-20TAB', 9),
('MED-LAX-LACTUL-667-120ML', 11),

-- Rehidratación oral
('MED-OTC-ORALSOL-SALES-4SOB', 60),
('MED-OTC-SUERO-ORAL-500ML', 0)         -- agotado
ON CONFLICT (sku) DO UPDATE
SET available_qty = EXCLUDED.available_qty,
    updated_at    = NOW();